ALTER TABLE rides
ADD COLUMN pickup_lat DOUBLE PRECISION DEFAULT 0.0,
ADD COLUMN pickup_lng DOUBLE PRECISION DEFAULT 0.0,
ADD COLUMN destination_lat DOUBLE PRECISION DEFAULT 0.0,
ADD COLUMN destination_lng DOUBLE PRECISION DEFAULT 0.0;